#! /bin/sh

# 1: URL , 2: reduction factor (0<x<1) , 3: port

# python3 -m http.server $3 &
python3 getsrc.py $1 
python3 getvalue.py $1
python3 getgoals.py $1 $2
python3 getnew.py $1 
# fuser -k -n tcp $3




